DROP TABLE IF EXISTS prices;

CREATE TABLE prices (
	BRAND_ID INT,
	START_DATE DATETIME,
	END_DATE DATETIME,
	PRICE_LIST INT,
	PRODUCT_ID INT,
	PRIORITY INT,
	PRICE DECIMAL(10,2), 
	CURR CHAR(3),
	PRIMARY KEY (PRODUCT_ID, PRICE_LIST)
);
