DROP TABLE IF EXISTS prices;

CREATE TABLE prices (
	PRICE_ID int NOT NULL AUTO_INCREMENT,
	BRAND_ID INT,
	START_DATE DATETIME,
	END_DATE DATETIME,
	PRICE_LIST INT,
	PRODUCT_ID INT,
	PRIORITY INT,
	PRICE DECIMAL(10,2), 
	CURR CHAR(3),
	PRIMARY KEY (PRICE_ID), 
	CONSTRAINT UC_Price UNIQUE (PRODUCT_ID, PRICE_LIST)
);
